version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: poultry_user
      POSTGRES_PASSWORD: poultry_pass
      POSTGRES_DB: poultry_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 